# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95d72b576fee8350790d920f6a20363f01683e02620407d3ee7407e1776ec09063c6f5942fd6784c230dc62cf5316737bde346d817222d58f4dd5a00b57b7466

test:
  secret_key_base: 52bd5aa47542ebe539b1275d545c21465f2df90904ed51ce684339ee3b3fc0edd4c13dc345aec2b2777250d5da2468e14f3861b8dcfe6e34ab7b9c2c22df721d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
